- name: Download K3s install script
  become: true
  get_url:
    url: https://get.k3s.io
    dest: "~/k3s_install.sh"
    mode: a+x

- name: Upgrade K3s
  become: true
  shell: >-
    K3S_URL=https://"{{ groups['master'][0] }}":6443
    K3S_TOKEN="{{ hostvars[groups['master'][0]]['node_token'] }}"
    ~/k3s_install.sh --kubelet-arg 'seccomp-default=true' >> ~/k3s_install_log.txt
  args:
    chdir: "~"
