- name: Download K3s install script
  become: true
  get_url:
    url: https://get.k3s.io
    dest: "~/k3s_install.sh"
    mode: a+x

- name: Upgrade K3s
  become: true
  shell: >-
    K3S_URL=https://"{{ groups['master'][0] }}":6443
    K3S_TOKEN="$(cat /var/lib/rancher/k3s/server/token)""
    ~/k3s_install.sh >> ~/k3s_install_log.txt
  args:
    chdir: "~"
