---
- name: Upgrade Kube Prometheus stack version
  become: true
  kubernetes.core.helm:
    name: kube-prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    reuse_values: true
    reset_values: false
    atomic: true
    update_repo_cache: true

- name: Upgrade Prometheus adapter version
  become: true
  kubernetes.core.helm:
    name: prometheus-adapter
    chart_ref: prometheus-community/prometheus-adapter
    release_namespace: monitoring
    reuse_values: true
    reset_values: false
    atomic: true
    update_repo_cache: true

- name: Upgrade Falco version
  become: true
  kubernetes.core.helm:
    name: falco
    chart_ref: falcosecurity/falco
    release_namespace: falco
    reuse_values: true
    reset_values: false
    atomic: true
    update_repo_cache: true

- name: Upgrade Falco exporter version
  become: true
  kubernetes.core.helm:
    name: falco-exporter
    chart_ref: falcosecurity/falco-exporter
    release_namespace: monitoring
    reuse_values: true
    reset_values: false
    atomic: true
    update_repo_cache: true
