- name: Download K3s install script
  become: true
  get_url:
    url: https://get.k3s.io
    dest: "~/k3s_install.sh"
    mode: a+x

- name: Upgrade K3s
  become: true
  shell: >-
    ~/k3s_install.sh --disable metrics-server >> ~/k3s_install_log.txt
  args:
    chdir: "~"

- name: Make local-storage provider non-default storage class
  become: true
  lineinfile: 
    path: /var/lib/rancher/k3s/server/manifests/local-storage.yaml
    regexp: '^    storageclass.kubernetes.io/is-default-class: "true"$' 
    line: '    storageclass.kubernetes.io/is-default-class: "false"'

- name: Get node token
  become: true
  command: cat /var/lib/rancher/k3s/server/node-token
  register: node_token_output

- name: Set node_token fact
  set_fact:
    node_token: "{{ node_token_output.stdout_lines[0] }}"
